MODEL:
  BACKBONE: resnext101_32x8d  # backbone: resnet50 or resnet101
  PRETRAINED: true        # use ImageNet pretrained weights
  NUM_CLASSES: 5          # 4 classes + background

DATA:
  ROOT_DIR: "data"       # root data directory containing 'train/' and 'test/'
  VAL_SPLIT: 0.1          # fraction of train set for validation
  NUM_WORKERS: 4          # DataLoader worker numbers

TRAIN:
  BATCH_SIZE: 2
  LR: 0.0001
  EPOCHS: 200
  WEIGHT_DECAY: 1e-4

TEST:
  BATCH_SIZE: 1
