model:
  backbone: resnet50
  pretrained: true
  num_classes: 5

train:
  batch_size: 1
  num_epochs: 20
  learning_rate: 0.005
  weight_decay: 0.0001
  step_size: 5
  gamma: 0.1

path:
  data_dir: ./data
  checkpoint_dir: ./outputs/checkpoints
